; maximum number of cars loaded at any given time
DEF MAX_NUM_CARS       EQU 8
; number of cars when map is loaded
DEF NUM_INITIAL_CARS   EQU 4
; number of different NPC car types that can be spawned
DEF NUM_SPAWNABLE_CARS EQU 8

; car constants
	const_def
	const BLACK_CAR ; $0
	const COP_CAR   ; $1
	const TAXI      ; $2
	const CAR_03    ; $3
	const CAR_04    ; $4
	const CAR_05    ; $5
	const BROWN_CAR ; $6
	const RED_CAR   ; $7
	const LIMOUSINE ; $8
	const CAR_09    ; $9
	const CAR_10    ; $a
DEF NUM_CAR_TYPES EQU const_value

RSRESET
DEF CARSTRUCT_FLAGS RB ; $00
DEF CARSTRUCT_01 RB ; $01
DEF CARSTRUCT_02 RB ; $02
DEF CARSTRUCT_03 RB ; $03
DEF CARSTRUCT_04 RB ; $04
DEF CARSTRUCT_05 RB ; $05
DEF CARSTRUCT_COORDS EQU _RS ; $06
DEF CARSTRUCT_Y_FRAC RB ; $06
DEF CARSTRUCT_Y RW ; $07
DEF CARSTRUCT_X_FRAC RB ; $09
DEF CARSTRUCT_X RW ; $0a
; direction is in 256th of a full circle
; (0 == 0 degrees, 256 == 360 degrees)
DEF CARSTRUCT_DIR RB ; $0c
; speed is (signed) q12 fixed precision
DEF CARSTRUCT_SPEED RW ; $0d
DEF CARSTRUCT_0F RB ; $0f
DEF CARSTRUCT_10 RB ; $10
DEF CARSTRUCT_11 RB ; $11
DEF CARSTRUCT_12 RB ; $12
DEF CARSTRUCT_13 RB ; $13
DEF CARSTRUCT_14 RB ; $14
DEF CARSTRUCT_15 RB ; $15
DEF CARSTRUCT_16 RB ; $16
DEF CARSTRUCT_17 RB ; $17
DEF CARSTRUCT_18 RB ; $18
DEF CARSTRUCT_19 RB ; $19
DEF CARSTRUCT_1A RB ; $1a
DEF CARSTRUCT_1B RB ; $1b
DEF CARSTRUCT_1C RB ; $1c
DEF CARSTRUCT_1D RB ; $1d
DEF CARSTRUCT_1E RB ; $1e
DEF CARSTRUCT_1F RB ; $1f
DEF CARSTRUCT_20 RB ; $20
DEF CARSTRUCT_21 RB ; $21
DEF CARSTRUCT_22 RB ; $22
DEF CARSTRUCT_ENT_PTR RW ; $23
DEF CARSTRUCT_SPRITE_PTR RW ; $25
DEF CAR_STRUCT_SIZE EQU _RS

; CARSTRUCT_FLAGS constants
	const_def
	const CARFLAG_ACTIVE_F ; 0
	const CARFLAG_PLAYER_F ; 1
	const CARFLAG_UNK2_F ; 2
	const CARFLAG_UNK3_F ; 3
	const CARFLAG_UNK4_F ; 4
	const CARFLAG_UNK5_F ; 5
	const CARFLAG_UNK6_F ; 6
	const CARFLAG_UNK7_F ; 7

DEF CARFLAG_ACTIVE EQU 1 << CARFLAG_ACTIVE_F
DEF CARFLAG_PLAYER EQU 1 << CARFLAG_PLAYER_F
DEF CARFLAG_UNK2 EQU 1 << CARFLAG_UNK2_F
DEF CARFLAG_UNK3 EQU 1 << CARFLAG_UNK3_F
DEF CARFLAG_UNK4 EQU 1 << CARFLAG_UNK4_F
DEF CARFLAG_UNK5 EQU 1 << CARFLAG_UNK5_F
DEF CARFLAG_UNK6 EQU 1 << CARFLAG_UNK6_F
DEF CARFLAG_UNK7 EQU 1 << CARFLAG_UNK7_F

RSRESET
DEF CARDATASTRUCT_0 RB ; $0
DEF CARDATASTRUCT_1 RB ; $1
DEF CARDATASTRUCT_2 RB ; $2
DEF CARDATASTRUCT_3 RB ; $3
DEF CARDATASTRUCT_4 RB ; $4
DEF CARDATASTRUCT_5 RB ; $5
DEF CARDATASTRUCT_TOP_SPEED RB ; $6
DEF CARDATASTRUCT_TOP_SPEED_REVERSE RB ; $7
DEF CARDATASTRUCT_8 RB ; $8
DEF CARDATASTRUCT_STEERING RB ; $9
DEF CARDATASTRUCT_A RB ; $a
DEF CARDATASTRUCT_B RW ; $b
DEF CARDATASTRUCT_D RW ; $d
DEF CARDATASTRUCT_F RW ; $f
DEF CAR_DATA_STRUCT_SIZE EQU _RS
