; game uses mostly ASCII encoding

	charmap "\0",        $00
	charmap " ",         $20
	charmap "!",         $21
	charmap "\"",        $22
	charmap "¡",         $23
	charmap "¿",         $24
	charmap "'",         $27
	charmap "\n",        $2a
	charmap ",",         $2c
	charmap "-",         $2d
	charmap ".",         $2e
	charmap "/",         $2f

	charmap "0",         $30
	charmap "1",         $31
	charmap "2",         $32
	charmap "3",         $33
	charmap "4",         $34
	charmap "5",         $35
	charmap "6",         $36
	charmap "7",         $37
	charmap "8",         $38
	charmap "9",         $39

	charmap ":",         $3a
	charmap "<",         $3c
	charmap ">",         $3e
	charmap "?",         $3f

	charmap "A",         $41
	charmap "B",         $42
	charmap "C",         $43
	charmap "D",         $44
	charmap "E",         $45
	charmap "F",         $46
	charmap "G",         $47
	charmap "H",         $48
	charmap "I",         $49
	charmap "J",         $4a
	charmap "K",         $4b
	charmap "L",         $4c
	charmap "M",         $4d
	charmap "N",         $4e
	charmap "O",         $4f
	charmap "P",         $50
	charmap "Q",         $51
	charmap "R",         $52
	charmap "S",         $53
	charmap "T",         $54
	charmap "U",         $55
	charmap "V",         $56
	charmap "W",         $57
	charmap "X",         $58
	charmap "Y",         $59
	charmap "Z",         $5a

	charmap "<BIG_Á>",   $5b
	charmap "<BIG_É>",   $5c
	charmap "<BIG_Í>",   $5d
	charmap "<BIG_Ó>",   $5e
	charmap "<BIG_Ú>",   $5f
	charmap "<BIG_À>",   $60

	; lowercase letters represent highlighted uppercase letters
	charmap "a",         $61
	charmap "b",         $62
	charmap "c",         $63
	charmap "d",         $64
	charmap "e",         $65
	charmap "f",         $66
	charmap "g",         $67
	charmap "h",         $68
	charmap "i",         $69
	charmap "j",         $6a
	charmap "k",         $6b
	charmap "l",         $6c
	charmap "m",         $6d
	charmap "n",         $6e
	charmap "o",         $6f
	charmap "p",         $70
	charmap "q",         $71
	charmap "r",         $72
	charmap "s",         $73
	charmap "t",         $74
	charmap "u",         $75
	charmap "v",         $76
	charmap "w",         $77
	charmap "x",         $78
	charmap "y",         $79
	charmap "z",         $7a

	charmap "<CTRL_80>", $80
	charmap "<CTRL_81>", $81
	charmap "<CTRL_82>", $82
	charmap "<CTRL_83>", $83
	charmap "<CTRL_84>", $84
	charmap "<CTRL_85>", $85
	charmap "<CTRL_86>", $86
	charmap "<CTRL_8F>", $8f

	charmap "Á",         $9b
	charmap "É",         $9c
	charmap "Í",         $9d
	charmap "Ó",         $9e
	charmap "Ú",         $9f
	charmap "À",         $a0
	charmap "È",         $a1
	charmap "Ì",         $a2
	charmap "Ò",         $a3
	charmap "Ù",         $a4
	charmap "Ä",         $a5
	charmap "Ë",         $a6
	charmap "Ï",         $a7
	charmap "Ö",         $a8
	charmap "Ü",         $a9
	charmap "Â",         $aa
	charmap "Ê",         $ab
	charmap "Î",         $ac
	charmap "Ô",         $ad
	charmap "Û",         $ae
	charmap "Ñ",         $af
	charmap "Ç",         $b0
	charmap "Æ",         $b1
	charmap "Œ",         $b2
	charmap "ß",         $b3

	charmap "á",         $db
	charmap "é",         $dc
	charmap "í",         $dd
	charmap "ó",         $de
	charmap "ú",         $df
	charmap "à",         $e0
	charmap "è",         $e1
	charmap "ì",         $e2
	charmap "ò",         $e3
	charmap "ù",         $e4
	charmap "ä",         $e5
	charmap "ë",         $e6
	charmap "ï",         $e7
	charmap "ö",         $e8
	charmap "ü",         $e9
	charmap "â",         $ea
	charmap "ê",         $eb
	charmap "î",         $ec
	charmap "ô",         $ed
	charmap "û",         $ee
	charmap "ñ",         $ef
	charmap "ç",         $f0
	charmap "æ",         $f1
	charmap "œ",         $f2
	charmap "<ß>",       $f3

	; these are highlighted versions of special characters
	charmap "<¡>",       $f9
	charmap "<!>",       $fa
	charmap "<,>",       $fb
	charmap "<5>",       $fc
	charmap "<->",       $fd
	charmap "<.>",       $fe
	charmap "<'>",       $ff
