; city constants
	const_def
	const MIAMI       ; $0
	const LOS_ANGELES ; $1
	const NEW_YORK    ; $2

; wGameMode constants
	const_def
	const MODE_TAKE_A_RIDE ; $0
	const MODE_UNK1        ; $1
	const MODE_UNK2        ; $2
	const MODE_UNK3        ; $3
	const MODE_UNK4        ; $4
	const MODE_UNDERCOVER  ; $5
	const MODE_CREDITS     ; $6

; mission constants
	const_def
DEF MIAMI_MISSIONS EQU const_value
	const MISSION_THE_BANK_JOB               ; $0
	const MISSION_HIDE_THE_EVIDENCE          ; $1
	const MISSION_BOAT_CHASE                 ; $2
	const MISSION_RAM_RAID_RACE              ; $3
	const MISSION_SUPERFLY_DRIVE             ; $4
	const MISSION_BAIT_FOR_A_TRAP            ; $5
	const MISSION_TAKE_OUT_DIANGELO          ; $6
DEF LOS_ANGELES_MISSIONS EQU const_value
	const MISSION_STEAL_A_COP_CAR            ; $7
	const MISSION_GET_LUCKY_TO_THE_DOCS      ; $8
	const MISSION_BEVERLY_HILLS_GET_AWAY     ; $9
DEF NEW_YORK_MISSIONS EQU const_value
	const MISSION_GRAND_CENTRAL_STATION      ; $a
	const MISSION_TRASH_GRANGERS_WHEELS      ; $b
	const MISSION_STOP_GRANGERS_GANG         ; $c
	const MISSION_CHASE_ONE_OF_GRANGERS_BOYS ; $d
	const MISSION_CROSS_TOWN_RECORD          ; $e
DEF NUM_MISSIONS EQU const_value

; car constants
	const_def
	const CAR_00 ; $0
	const CAR_01 ; $1
	const CAR_02 ; $2
	const CAR_03 ; $3
	const CAR_04 ; $4
	const CAR_05 ; $5
	const CAR_06 ; $6
	const CAR_07 ; $7
	const CAR_08 ; $8
	const CAR_09 ; $9
	const CAR_10 ; $a

RSRESET
DEF CARDATASTRUCT_0 RB ; $0
DEF CARDATASTRUCT_1 RB ; $1
DEF CARDATASTRUCT_2 RB ; $2
DEF CARDATASTRUCT_3 RB ; $3
DEF CARDATASTRUCT_4 RB ; $4
DEF CARDATASTRUCT_5 RB ; $5
DEF CARDATASTRUCT_MAX_SPEED RB ; $6
DEF CARDATASTRUCT_MAX_SPEED_REVERSE RB ; $7
DEF CARDATASTRUCT_8 RB ; $8
DEF CARDATASTRUCT_TURNING RB ; $9
DEF CARDATASTRUCT_A RB ; $a
DEF CARDATASTRUCT_B RW ; $b
DEF CARDATASTRUCT_D RW ; $d
DEF CARDATASTRUCT_F RW ; $f

RSRESET
DEF CARSTRUCT_FLAGS RB ; $00
DEF CARSTRUCT_01 RB ; $01
DEF CARSTRUCT_02 RB ; $02
DEF CARSTRUCT_03 RB ; $03
DEF CARSTRUCT_04 RB ; $04
DEF CARSTRUCT_05 RB ; $05
DEF CARSTRUCT_06 RB ; $06
DEF CARSTRUCT_07 RW ; $07
DEF CARSTRUCT_09 RB ; $09
DEF CARSTRUCT_0A RW ; $0a
DEF CARSTRUCT_0C RB ; $0c
DEF CARSTRUCT_SPEED RW ; $0d
DEF CARSTRUCT_0F RB ; $0f
DEF CARSTRUCT_10 RB ; $10
DEF CARSTRUCT_11 RB ; $11
DEF CARSTRUCT_12 RB ; $12
DEF CARSTRUCT_13 RB ; $13
DEF CARSTRUCT_14 RB ; $14
DEF CARSTRUCT_15 RB ; $15
DEF CARSTRUCT_16 RB ; $16
DEF CARSTRUCT_17 RB ; $17
DEF CARSTRUCT_18 RB ; $18
DEF CARSTRUCT_19 RB ; $19
DEF CARSTRUCT_1A RB ; $1a
DEF CARSTRUCT_1B RB ; $1b
DEF CARSTRUCT_1C RB ; $1c
DEF CARSTRUCT_1D RB ; $1d
DEF CARSTRUCT_1E RB ; $1e
DEF CARSTRUCT_1F RB ; $1f
DEF CARSTRUCT_20 RB ; $20
DEF CARSTRUCT_21 RB ; $21
DEF CARSTRUCT_22 RB ; $22
DEF CARSTRUCT_ENT_PTR RW ; $23
DEF CARSTRUCT_25 RW ; $25
DEF CAR_STRUCT_SIZE EQU _RS

; CARSTRUCT_FLAGS constants
	const_def
	const CARFLAG_ACTIVE_F ; 0
	const CARFLAG_PLAYER_F ; 1
	const CARFLAG_UNK2_F ; 2
	const CARFLAG_UNK3_F ; 3
	const CARFLAG_UNK4_F ; 4
	const CARFLAG_UNK5_F ; 5
	const CARFLAG_UNK6_F ; 6
	const CARFLAG_UNK7_F ; 7

DEF CARFLAG_ACTIVE EQU 1 << CARFLAG_ACTIVE_F
DEF CARFLAG_PLAYER EQU 1 << CARFLAG_PLAYER_F
DEF CARFLAG_UNK2 EQU 1 << CARFLAG_UNK2_F
DEF CARFLAG_UNK3 EQU 1 << CARFLAG_UNK3_F
DEF CARFLAG_UNK4 EQU 1 << CARFLAG_UNK4_F
DEF CARFLAG_UNK5 EQU 1 << CARFLAG_UNK5_F
DEF CARFLAG_UNK6 EQU 1 << CARFLAG_UNK6_F
DEF CARFLAG_UNK7 EQU 1 << CARFLAG_UNK7_F

; world props
	const_def
	const PROP_0 ; $0
	const PROP_1 ; $1
	const PROP_2 ; $2
	const PROP_3 ; $3
	const PROP_4 ; $4
	const PROP_5 ; $5
	const PROP_6 ; $6
	const PROP_7 ; $7
	const PROP_8 ; $8
	const PROP_9 ; $9
	const PROP_A ; $a
	const PROP_B ; $b
	const PROP_C ; $c
	const PROP_D ; $d

; maximum damage the player's car can take
; corresponds to 8 pixels times 7 damage bar tiles
DEF MAX_DAMAGE EQU 8 * 7

; maximum felony the player can accumulate
; corresponds to 8 pixels times 7 damage bar tiles
DEF MAX_FELONY EQU 8 * 7

DEF NUM_CITY_PROPS EQU 8 ; how many props in stage

; wTimerMode constants
DEF TIMER_MODE_COUNT_DOWN EQU $1
DEF TIMER_MODE_COUNT_UP   EQU $2
