; entity struct constants
RSRESET
DEF ENT_FLAGS            RB     ; $00
DEF ENT_UPDATE_TIMER     RB     ; $01
DEF ENT_UPDATE_FUNC_BANK RB     ; $02
DEF ENT_STACK_POINTER    RW     ; $03
DEF ENT_UNK05            RB     ; $05
DEF ENT_CAR_PTR          RW     ; $06
DEF ENT_STACK            RB $50 ; $08
DEF ENT_STACK_BOTTOM EQU _RS    ; $58
DEF ENT_STRUCT_SIZE EQU _RS

DEF NUM_ENTITIES EQU 32

; flags for ENT_FLAGS
	const_def
	const ENTF_ACTIVE_F ; 0

DEF ENTF_ACTIVE EQU 1 << ENTF_ACTIVE_F
