; Boolean checks
DEF FALSE EQU 0
DEF TRUE  EQU 1

DEF NONE EQU 0

; wActiveCheats flags
	const_def
	const CHEATS_UNLOCKED_F       ; 0
	const CHEAT_NO_DAMAGE_F       ; 1
	const CHEAT_IMMUNITY_F        ; 2
	const CHEAT_OPEN_ALL_CITIES_F ; 3
	const CHEAT_TEST_STUFF_F      ; 4

DEF CHEATS_UNLOCKED       EQU 1 << CHEATS_UNLOCKED_F
DEF CHEAT_NO_DAMAGE       EQU 1 << CHEAT_NO_DAMAGE_F
DEF CHEAT_IMMUNITY        EQU 1 << CHEAT_IMMUNITY_F
DEF CHEAT_OPEN_ALL_CITIES EQU 1 << CHEAT_OPEN_ALL_CITIES_F
DEF CHEAT_TEST_STUFF      EQU 1 << CHEAT_TEST_STUFF_F
