RSRESET
DEF SPRITESTRUCT_FLAGS RB
DEF SPRITESTRUCT_UNK01 RB
DEF SPRITESTRUCT_Y     RW
DEF SPRITESTRUCT_UNK04 RB
DEF SPRITESTRUCT_X     RW
DEF SPRITESTRUCT_UNK07 RB
DEF SPRITESTRUCT_UNK08 RB
DEF SPRITESTRUCT_UNK09 RW
DEF SPRITESTRUCT_UNK0B RW
DEF _RS = $11
DEF SPRITE_STRUCT_SIZE EQU _RS

	const_def
	const SPRITEFLAG_ACTIVE_F ; 0
	const SPRITEFLAG_UNK1_F ; 1
	const SPRITEFLAG_UNK2_F ; 2
	const SPRITEFLAG_UNK3_F ; 3
	const SPRITEFLAG_UNK4_F ; 4
	const SPRITEFLAG_XFLIP_F ; 5
	const SPRITEFLAG_YFLIP_F ; 6
	const SPRITEFLAG_UNK7_F ; 7

DEF SPRITEFLAG_ACTIVE EQU 1 << SPRITEFLAG_ACTIVE_F
DEF SPRITEFLAG_UNK1 EQU 1 << SPRITEFLAG_UNK1_F
DEF SPRITEFLAG_UNK2 EQU 1 << SPRITEFLAG_UNK2_F
DEF SPRITEFLAG_UNK3 EQU 1 << SPRITEFLAG_UNK3_F
DEF SPRITEFLAG_UNK4 EQU 1 << SPRITEFLAG_UNK4_F
DEF SPRITEFLAG_XFLIP EQU 1 << SPRITEFLAG_XFLIP_F
DEF SPRITEFLAG_YFLIP EQU 1 << SPRITEFLAG_YFLIP_F
DEF SPRITEFLAG_UNK7 EQU 1 << SPRITEFLAG_UNK7_F

DEF NUM_OAM_GROUPS EQU 10 ; how many groups per Virtual OAM
DEF OAM_GROUP_SIZE EQU 20 ; how many OAMs can each group contain

DEF OAM_GROUP_STRUCT_SIZE EQU 1 + OAM_GROUP_SIZE * OBJ_SIZE

; wSprites struct constants
DEF NUM_SPRITE_STRUCTS EQU $20
