RSRESET
DEF SPRITESTRUCT_FLAGS  RB ; $00
DEF SPRITESTRUCT_UNK01  RB ; $01
DEF SPRITESTRUCT_Y      RW ; $02
DEF SPRITESTRUCT_UNK04  RB ; $04
DEF SPRITESTRUCT_X      RW ; $05
DEF SPRITESTRUCT_HEIGHT RB ; $07
DEF SPRITESTRUCT_WIDTH  RB ; $08
DEF SPRITESTRUCT_TILE_1 RB ; $09
DEF SPRITESTRUCT_ATTR_1 RB ; $0a
DEF SPRITESTRUCT_TILE_2 RB ; $0b
DEF SPRITESTRUCT_ATTR_2 RB ; $0c
DEF SPRITESTRUCT_UNK0D  RB ; $0d
DEF SPRITESTRUCT_UNK0E  RB ; $0e
DEF SPRITESTRUCT_UNK0F  RB ; $0f
DEF SPRITESTRUCT_UNK10  RB ; $10
DEF SPRITE_STRUCT_SIZE EQU _RS

	const_def
	const SPRITEFLAG_ACTIVE_F  ; 0
	const SPRITEFLAG_VISIBLE_F ; 1
	const SPRITEFLAG_FIXED_F   ; 2
	const SPRITEFLAG_UNK3_F    ; 3
	const SPRITEFLAG_UNK4_F    ; 4
	const SPRITEFLAG_XFLIP_F   ; 5
	const SPRITEFLAG_YFLIP_F   ; 6
	const SPRITEFLAG_UNK7_F    ; 7

DEF SPRITEFLAG_ACTIVE  EQU 1 << SPRITEFLAG_ACTIVE_F
DEF SPRITEFLAG_VISIBLE EQU 1 << SPRITEFLAG_VISIBLE_F
DEF SPRITEFLAG_FIXED   EQU 1 << SPRITEFLAG_FIXED_F
DEF SPRITEFLAG_UNK3    EQU 1 << SPRITEFLAG_UNK3_F
DEF SPRITEFLAG_UNK4    EQU 1 << SPRITEFLAG_UNK4_F
DEF SPRITEFLAG_XFLIP   EQU 1 << SPRITEFLAG_XFLIP_F
DEF SPRITEFLAG_YFLIP   EQU 1 << SPRITEFLAG_YFLIP_F
DEF SPRITEFLAG_UNK7    EQU 1 << SPRITEFLAG_UNK7_F

DEF NUM_OAM_GROUPS EQU 10 ; how many groups per Virtual OAM
DEF OAM_GROUP_SIZE EQU 20 ; how many OAMs can each group contain

DEF OAM_GROUP_STRUCT_SIZE EQU 1 + OAM_GROUP_SIZE * OBJ_SIZE

; wSprites struct constants
DEF NUM_SPRITE_STRUCTS EQU $20
