INCLUDE "home/header.asm"

SECTION "Home", ROM0

INCLUDE "home/start.asm"
INCLUDE "home/scene.asm"
INCLUDE "home/empty_screen.asm"
INCLUDE "data/scenes.asm"
INCLUDE "home/vblank.asm"
INCLUDE "home/stat.asm"
INCLUDE "home/timer.asm"
INCLUDE "home/serial.asm"
INCLUDE "home/post_vblank.asm"
INCLUDE "home/joypad.asm"
INCLUDE "home/decompress.asm"
INCLUDE "home/memory.asm"
INCLUDE "home/math_16bit.asm"
INCLUDE "home/random.asm"
INCLUDE "home/far_call_hl.asm"
INCLUDE "home/copy_tiles.asm"
INCLUDE "home/coordinates.asm"
INCLUDE "home/push_tiles.asm"
INCLUDE "home/func_bdd.asm"
INCLUDE "home/math.asm"
INCLUDE "home/double_speed.asm"
INCLUDE "home/color.asm"
INCLUDE "home/audio.asm"
INCLUDE "home/struct.asm"
INCLUDE "home/oam.asm"
INCLUDE "home/entity.asm"
INCLUDE "home/game_loop.asm"
INCLUDE "home/home.asm"
